# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8bb6639f956032a8c9d0a9fcb259401bfc4ee01a3cc93b334dd356ba2f5975c9872d726d4c557a4e44ea74033f7c6459e0bc62b776548a649375c94ac94173f

test:
  secret_key_base: eac0781fdb6330af05c4b912deaef2a8843994f90d53c64571eb57cddd851ff91e7098add2888d0eb9e2bb989185bd0906c4434bbe19bd34e6bd317df0e1b11c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
